name: CI/CD Tests

on: 
  push:
      branches:
      - main
      - review

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version: 
          - "3.14"

    steps:
      - name: Checking config REMOTE_URL_RAW value
        run: |
          python script/review_config.py
